### ISSUE TITLE
 datasets

### ISSUE THREAD

**Issue by 123yuyu** [giles200619/VI-GAN#1]
Hi, can you share your datasets?

**Comment by giles200619** [comment]
Hi,
try this out: 
https://drive.google.com/file/d/1CEFnMvPYiXIwq3jnHgJPKkAwcm6IXNsp/view?usp=sharing

**Comment by giles200619** [comment]
> Hi, can you share your datasets?
Hi,
try this out: 
https://drive.google.com/file/d/1CEFnMvPYiXIwq3jnHgJPKkAwcm6IXNsp/view?usp=sharing
